### ISSUE TITLE
No programatic access

### ISSUE THREAD

**Issue by hollowdoor** [busterc/microgen#1]
This looks really cool, but I was wondering what you think of making it both command line, and programmatic with an exported function.

It's not a huge problem. I haven't even tried it yet. :)

**Comment by busterc** [comment]
Thanks. 

For programmatic use you should just use [handlebars](https://github.com/wycats/handlebars.js/). It's what microgen is using under the hood and you can do so much more with it than what microgen is able to offer via the CLI prompt. The beauty of microgen is that it simply provides a CLI prompt for files with _simple_ handlebars placeholders, which is missing from the official and other 3rd party handlebars modules.

**Comment by hollowdoor** [comment]
The CLI prompt is what I want. XD

Sorry I wasn't clear. I know about handlebars. I want that beauty you were talking about with microgen with the the auto CLI prompt made from a handlebars template, but with programmatic access. It's the part I think is cool. You don't have to if you don't want to, but that's really what I want. That specific functionality. :)

If you prefer I can do a pull request.

**Comment by busterc** [comment]
Hmm, I guess I'm not understanding your use case. Certainly feel free to do a PR.

**Comment by hollowdoor** [comment]
I like the idea of easy usage by prompt, but I'm thinking that microgen could fit into larger applications. I already have templates that I use to generate new projects, but no prompt. Maybe for task runners, or some other larger compound scripts.

I already have a plan for how to make microgen programmatic. I'll see if I can get the time to work on it before the end of next week.

**Comment by hollowdoor** [comment]
What would be your policy for callbacks vs. returning a promise when a call to microgen completes. That is for if, and when I do the PR to expose microgen programmaticly. :)

**Comment by busterc** [comment]
If it's an either/or decision then go with promises.

**Comment by hollowdoor** [comment]
That would be my preference.
