### ISSUE TITLE
add node.js api

### ISSUE THREAD

**Issue by ungoldman** [busterc/microgen#3]
Would be cool to be able to use this module programmatically too! Is that something you're open to?

**Comment by hollowdoor** [comment]
+1 I already posted an issue about the same thing. #1

**Comment by ungoldman** [comment]
Ah sorry I didn't see that earlier. My use case is a little different though, I wouldn't want the CLI. I'm already using handlebars in https://github.com/ungoldman/module-init (example: https://github.com/ungoldman/module-init/blob/master/templates/package.json.mustache) and was hoping to offload some of the complexity to microgen but it may be more trouble than it's worth.

**Comment by hollowdoor** [comment]
Well #1 got closed anyway. You probably couldn't see it because of the issue filter. I'm still waiting for a reply on that one.
